### ISSUE TITLE
Display ALA-cited publications on ALA website

### ISSUE THREAD

**Issue by CorinnaPaeper** [AtlasOfLivingAustralia/ala-metrics-and-impact#25]
Integrate Wordpress Zotero plugin (https://github.com/davidswelt/zot_bib_web) into ALA website to enable displaying of publications that have cited the ALA (01 - ALA Used).

Prerequisite: Implement a data curation system for journal articles based on how much the ALA was utilised for the publication; tag publications.

**Comment by matthewandrews** [comment]
This was released in mid-November.
